Bidirectional streaming RPC
ITIS-IoT-team/itis_iot_classes pull request #2
Opened 2020-03-29 18:09 UTC by RomanKlimov

2020-03-29 22:03 UTC, bulat-gini requested changes
Надо переместить в папочку grpc
bidirectional_streaming >> /grpc/bidirectional_streaming

2020-03-29 22:05 UTC, BulatGin commented
А в java сгенерированные файлики не добавляются?

2020-03-30 20:15 UTC, AnnaaNovikova commented
lgtm)

2020-03-30 20:45 UTC, bulat-gini approved these changes
lgtm

2020-03-30 20:45 UTC, merged